# Generated by Django 3.2.7 on 2022-01-15 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_zip_code_profile_zip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
